### ISSUE TITLE
Internacionalização do projeto

### ISSUE THREAD

**Issue by SandroMoretti** [VisiComp/craftbeerpi4-ui#1]
Fazer o projeto em multi idiomas.
Utilizar a dependência i18next do react, que é uma biblioteca para internacionalização de projetos react.

https://www.npmjs.com/package/react-i18next

**Comment by gestao-planeta** [comment]
Favor registar o que foi feito.

**Comment by ArthurZica** [comment]
Tarefas Gerais do projeto:

- [x] Adcionar i18next ao projeto.

- [x] Traduzir Menu Lateral.

- [x] Traduzir Pagina About.

- [x] Traduzir Pagina Settings.

- [x] Traduzir Pagina Dashboard.

- [x] Traduzir Pagina MashProfile.

- [x] Traduzir Pagina Hardware.

- [x] Traduzir Pagina Fermenter Profile.

- [x] Traduzir Pagina Analytics.

- [x] Traduzir Pagina Plugins.

- [x] Traduzir Pagina System.

- [x] Traduzir Pagina Recipe Upload.

- [x]  Adcionar Botões para mudança de idioma.

- [x] Traduzir Alertas e Dialogos adcionais.

**Comment by ArthurZica** [comment]
Feitas traduções e ajustes nas tabelas e formulários da pagina hardware
**Antes:**


![image](https://user-images.githubusercontent.com/95576985/171738470-6e752ab9-44ac-4478-9ec0-fe403c3be03c.png)
![image](https://user-images.githubusercontent.com/95576985/171738499-63d4376b-4c4d-447b-a95d-e2667b177e05.png)
![image](https://user-images.githubusercontent.com/95576985/171738512-52e9274a-a24d-4fea-babc-4efaeedc2317.png)
![image](https://user-images.githubusercontent.com/95576985/171738554-21c47d51-0094-47d9-93a5-1589cf9d8af1.png)


Depois:
![image](https://user-images.githubusercontent.com/95576985/171738590-77631fd6-607e-4d5a-a7ae-54d6ed326094.png)
![image](https://user-images.githubusercontent.com/95576985/171738654-a0b3bdf4-3abb-499e-844b-c4d04764d342.png)
![image](https://user-images.githubusercontent.com/95576985/171738712-98a0d5f1-cd5c-497d-a12a-8185e4f3818c.png)

**Comment by ArthurZica** [comment]
Foram feitas modificações em todos formulários para possibilitar a tradução de alguns itens que antes não eram possíveis, também foi traduzido completamente o formulário da pagina "hardware" finalizando assim a tradução da mesma.


![image](https://user-images.githubusercontent.com/95576985/172246667-5fd748a8-d603-44de-8cf9-1a17ef99c708.png)
alguns itens de formulário como a legenda "Trocar a logica da Fermentadora automaticamente entre ligado e desligado -> Sim" não estavam aceitando a tradução, foram feitas alterações e agora praticamente todos itens dos formulários estão traduzidos.

A pagina Hardware teve todos os formulários completamente traduzidos, finalizando assim a tradução da mesma.

**Comment by ArthurZica** [comment]
Foram Corrigidos todos formularios, traduzido o menu lateral da aba "Dashboardlayer",Corrigido elementos que não traduziam da pagina "settings" e traduzidos os nomes dos elementos da aba "DashboardLayer".



Antes:

![image](https://user-images.githubusercontent.com/95576985/172480764-edb5b795-baa6-4532-aa49-7507709d58e5.png)
![image](https://user-images.githubusercontent.com/95576985/172480861-59bb6690-dd93-4e6c-a861-87a588c4ee4c.png)
![image](https://user-images.githubusercontent.com/95576985/172480908-58c454a0-9fb9-4ca2-ba9a-d1cd2eaec0b6.png)


Depois:

![image](https://user-images.githubusercontent.com/95576985/172481031-85bc59dd-eb38-45a6-9527-2da94876cd13.png)
![image](https://user-images.githubusercontent.com/95576985/172481089-1e704d9e-57d9-468f-859c-1b415b66ee81.png)
![image](https://user-images.githubusercontent.com/95576985/172481254-493a5ddd-4049-4809-945c-b26eea0197ab.png)



No momento faltam apenas traduzir alguns elementos da pasta "Widgets", fazer testes para verificar possiveis alertas não traduzidos e fazer ajustes no botão de troca de idiomas passando ele para a pagina settings.

**Comment by ArthurZica** [comment]
Foram feitos ajustes na aba dashboard, traduzindo seus widgets:

![image](https://user-images.githubusercontent.com/95576985/172715275-e76813e3-54a5-4030-abf6-9775321b807f.png)

Também foram feitos pequenos ajustes em outras paginas e foi feito um teste para verificar elementos não traduzidos, aparentemente todos os elementos do programa estão traduzidos, finalizando assim a tradução.

Será necessário agora fazer ajustes para que o idioma selecionado pelo usuário fique salvo, ou que o programa detecte automaticamente através do browser.

**Comment by ArthurZica** [comment]
Foram feitos testes e montado um painel de controle para simular um processo real.

![image](https://user-images.githubusercontent.com/95576985/172946636-f8eb8ed0-544c-4ae1-a317-4f7afe00c27e.png)

Durante os testes foi verificado que alguns diálogos não estavam traduzidos.

![image](https://user-images.githubusercontent.com/95576985/172946779-cf5bc574-4e7f-470e-87c8-a58c275ad796.png)
 
Foram traduzidos então os dialogos de "set temp" e "set pressure".

![image](https://user-images.githubusercontent.com/95576985/172947000-7a235548-5fa9-4168-a909-b2330a6c869e.png)

**Comment by ArthurZica** [comment]
**Foram Traduzidos Diálogos que mostram na tela quando são completadas Etapas do processo:**


Antes:
![image](https://user-images.githubusercontent.com/95576985/173132759-a6e549ed-d75c-4d9e-85a8-cf8961410699.png)

![image](https://user-images.githubusercontent.com/95576985/173132799-fb77ffab-48d3-4d12-807b-643d27661df3.png)




Depois:

![image](https://user-images.githubusercontent.com/95576985/173132322-00c2a7b2-af11-437e-ace5-d9a747b3b5ea.png)


![image](https://user-images.githubusercontent.com/95576985/173132912-9ba96b15-a575-4bb5-98fc-aa8c5fbf8c95.png)

**Também foram traduzido os itens do widget "MashStep" :**

Antes:

![image](https://user-images.githubusercontent.com/95576985/173133488-358f022c-a52b-403d-ad10-cff2417805f7.png)
![image](https://user-images.githubusercontent.com/95576985/173133541-c2780d43-54ac-428c-81be-e1cdbc5cb028.png)


Depois:

![image](https://user-images.githubusercontent.com/95576985/173133581-c73f165e-9a79-4378-916c-7fa4e0f419f2.png)
![image](https://user-images.githubusercontent.com/95576985/173133644-1651022b-b340-4261-b42f-ebb3dc6e0458.png)


Não Encontrei uma solução para traduzir os alertas mostrados na tela quando se executa os processos, pois praticamente  todos eles tem um elemento variável ao final do texto.

Exemplo de Alerta:
![image](https://user-images.githubusercontent.com/95576985/173134158-2a215955-c4a9-4cae-856e-06331a9ec720.png)

No Código:
![image](https://user-images.githubusercontent.com/95576985/173134344-aa5ddb86-9b8c-42d0-af1d-64ff4a5ab81d.png)

Para Traduzir teria que pegar cada possível frase e adicionar no arquivo translation.json, como tem um elemento variavel no final de cada frase seria impossivel fazer isso da maneira que eu imaginava. Portanto esses alertas seguem sem tradução até que seja encontrada uma solução.


**Os botões de ação do widget Steps também foram traduzidos:**

Antes:


![image](https://user-images.githubusercontent.com/95576985/173146670-0c8a5c1f-59bb-4bf7-b88e-10356144fa5b.png)



Depois:

![image](https://user-images.githubusercontent.com/95576985/173146561-3bd5a025-45b2-47aa-84fe-9168d425839c.png)

**Comment by ArthurZica** [comment]
**O "Resumo" Da Pagina Mashprofile foi parcialmente traduzido, novamente alguns dos dialogos tem variaveis como horario e outros, dificultando a tradução, portanto foi traduzido o que era possivel.**

Antes:
![image](https://user-images.githubusercontent.com/95576985/173438795-60d8cc27-5e6f-4469-a275-61433077bb0c.png)


Depois:
![image](https://user-images.githubusercontent.com/95576985/173438824-589b2703-eefa-46fb-9dad-b50769285bae.png)


**Existem Plugins para adicionar o processo de PID ao craftbeerpi e eles foram instalados, porém todo plugin que for instalado será necessario traduzir os elementos adicionais do plugin.**

Exemplo de plugin sem tradução:
![image](https://user-images.githubusercontent.com/95576985/173439683-f51d40b0-39ed-4635-ba19-2ca016c8429b.png)

Exemplo de plugin traduzido:
![image](https://user-images.githubusercontent.com/95576985/173439734-31e3304d-5500-449b-bc8b-b8867061cc64.png)

Pode se notar que o propsedit_ ou outro prefixo pode aparecer na tela ao adicionar um plugin, será necessário buscar uma solução para isso.

**Foi Adicionado no código funções para possibilitar que o programa capture automaticamente a linguagem através da linguagem do navegador, porém não funcionou e vem com a linguagem padrão em inglês. Apesar disso agora a linguagem selecionada fica salva e mesmo após dar f5 ou fechar e abrir o navegador a linguagem selecionada continua.**

**Comment by ArthurZica** [comment]
**Foi retirado toda linha de código que continha "propsedit_" para que os plugins que fossem adicionados não gerassem bugs**

**Foi configurado o botão de seleção de idiomas na pagina setttings porém falta faze-lo mudar de idiomas de fato**

botão:
![image](https://user-images.githubusercontent.com/95576985/173686873-cb2dd0c3-b3ef-4a61-a1b0-986e3ac22112.png)

**Também foi corrigido o arquivo i18n.js e agora o programa puxa automaticamente a lingua padrão do navegador.**

Foi Decidido não traduzir os alertas como esse:
![image](https://user-images.githubusercontent.com/95576985/173687211-9b7ae59f-154c-436d-8d51-484c85803275.png)

O projeto no momento se encontra quase finalizado tendo em vista que a unica tarefa restante é fazer o botão de mudanças de idioma da pagina settings funcionar e excluir o botão atual.

**Comment by ArthurZica** [comment]
Tentei Modificar o botão na pagina settings porém não consegui faze-lo funcionar, sendo a unica coisa restante para finalizar o projeto.

Provavelmente será finalizado no próximo dia de trabalho.

**Comment by ArthurZica** [comment]
**O Projeto Foi Finalizado e sua versão final está upada no repositório.** 

Nessa ultima versão foram:
Retirado Botões com as bandeiras no topo do programa.
Corrigido o botão de idiomas na pagina settings, agora ele funciona perfeitamente e exibe o valor da linguagem predefinida assim que a pagina é carregada. 
Retirado Pasta locales que estava no lugar errado.

Antes: 

![image](https://user-images.githubusercontent.com/95576985/174316005-c1404810-ce65-4d5c-9dce-2ce9aea14d74.png)



Depois:

![image](https://user-images.githubusercontent.com/95576985/174316067-c4ab2857-b83d-45a8-8df6-180b2a6218bb.png)

Como dito antes foi optado por não traduzir os alertas já que seria muito complicado e os plugins (exceto cbpiui) também não foram traduzidos, portanto só o programa nativo está totalmente traduzido mas suporta a tradução dos plugins.
